### ISSUE TITLE
A bout xunit framework

### ISSUE THREAD

**Issue by hayletdomybest** [natemcmaster/xunit-extensions#10]
Sorry to bother you, I am studying how to develop a unit-test-framework, and I see your project xunit-extensions, that's a good sample for me to understand how to work and what is my first step, but a very confuse question for me. That's why I can click run test button and my unit-test-framework will working, I don't know from the project can you tell me why and help me what document record this

**Comment by natemcmaster** [comment]
I don't understand the question. Please be more specific about which buttons you are talking about and what _exactly_ you are expecting to happen.

**Comment by hayletdomybest** [comment]
Sorry, I don't know why SkippableFactDiscoverer just inherent in FactDiscoverer, and run unit test the program will run this, not run original program of FactDiscoverer.

Because I attempt to create class name of MyTestFramework and inherent in XunitTestFramework,but unfortunately the program not run, it is still running native program.

Thank your response, and sorry ask to this question that not relate your project

**Comment by natemcmaster** [comment]
> why SkippableFactDiscoverer just inherent in FactDiscoverer

It's easier to inherit and add my customer functionality, as opposed to re-implementing the entire `IXunitTestCaseDiscoverer` interface.

> create class name of MyTestFramework and inherent in XunitTestFramework,but unfortunately the program not run

You might be missing the right assembly attributes, example https://github.com/xunit/samples.xunit/blob/master/AssemblyFixtureExample/Samples.cs#L5

Hope that helps.
